// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkvMXMmAOM0J1zlo5TUoMhIz43ljArKOI',
    appId: '1:133460755008:web:8a656616a94cb182e3d5a5',
    messagingSenderId: '133460755008',
    projectId: 'zerohunger-logistics',
    authDomain: 'zerohunger-logistics.firebaseapp.com',
    storageBucket: 'zerohunger-logistics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXIvwOejyGPaUR5WvXlB7BxAnxl7kEkVo',
    appId: '1:133460755008:android:2f931d90f00a6764e3d5a5',
    messagingSenderId: '133460755008',
    projectId: 'zerohunger-logistics',
    storageBucket: 'zerohunger-logistics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-AjULTpi6pKoexuzIDeodbBk1plXDag',
    appId: '1:133460755008:ios:7f0044638ad58f5ce3d5a5',
    messagingSenderId: '133460755008',
    projectId: 'zerohunger-logistics',
    storageBucket: 'zerohunger-logistics.appspot.com',
    iosBundleId: 'com.example.zerohungerLogisticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-AjULTpi6pKoexuzIDeodbBk1plXDag',
    appId: '1:133460755008:ios:7f0044638ad58f5ce3d5a5',
    messagingSenderId: '133460755008',
    projectId: 'zerohunger-logistics',
    storageBucket: 'zerohunger-logistics.appspot.com',
    iosBundleId: 'com.example.zerohungerLogisticsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkvMXMmAOM0J1zlo5TUoMhIz43ljArKOI',
    appId: '1:133460755008:web:5f346ee87253c6fee3d5a5',
    messagingSenderId: '133460755008',
    projectId: 'zerohunger-logistics',
    authDomain: 'zerohunger-logistics.firebaseapp.com',
    storageBucket: 'zerohunger-logistics.appspot.com',
  );
}
